# Generated by Django 4.2.6 on 2024-04-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Protocol', models.BigIntegerField()),
                ('FlowDuration', models.BigIntegerField()),
                ('FPLengthTotal', models.BigIntegerField()),
                ('FlowBytesPers', models.BigIntegerField()),
                ('FlowPacketsPers', models.BigIntegerField()),
                ('FwdIATTotal', models.BigIntegerField()),
                ('PacketLengthMean', models.BigIntegerField()),
                ('AvgPacketSize', models.BigIntegerField()),
                ('AvgFwdSegmentSize', models.BigIntegerField()),
                ('SourceIP', models.BigIntegerField()),
            ],
        ),
    ]
